version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goweb
    restart: always
    #working_dir: "/srv"
    #entrypoint: ["tail", "-f", "/dev/null"]
    labels:
      - "traefik.http.routers.web.rule=Host(`web.local.seanhome.xyz`)"
      - "traefik.http.services.web.loadbalancer.server.port=8080"

networks:
  default:
    external:
      name: traefik_default
