apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ing
spec:
  rules:
  - host: {{ .Values.name }}.local.seanhome.xyz
    http:
      paths:
      - backend: 
          serviceName: {{ .Values.name }}-svc
          servicePort: {{ .Values.SVCPort }}
        path: /
