package jokes

var Jokes map[string]string = map[string]string {
  "0": "What's red and bad for your teeth? A Brick.",
  "1": "Why are graveyards so noisy? Because of all the coffin.",
  "2": "I'm afraid for the calendar. Its days are numbered.",
  "3": "My wife said I should do lunges to stay in shape. That would be a big step forward.",
  "4": "Why do fathers take an extra pair of socks when they go golfing?" "In case they get a hole in one!",
  "5": "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
  "6": "What do a tick and the Eiffel Tower have in common?" "They're both Paris sites.",
  "7": "What do you call a fish wearing a bowtie?" "Sofishticated.",
  "8": "How do you follow Will Smith in the snow?" "You follow the fresh prints.",
  "9": "If April showers bring May flowers, what do May flowers bring?" "Pilgrims.",
  "10": "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
  "11": "What do you call a factory that makes okay products?" "A satisfactory.",
  "12": "Dear Math, grow up and solve your own problems.",
  "13": "What did the janitor say when he jumped out of the closet?" "Supplies!",
  "14": "Have you heard about the chocolate record player? It sounds pretty sweet.",
  "15": "What did the ocean say to the beach?" "Nothing, it just waved.",
  "16": "Why do seagulls fly over the ocean?" "Because if they flew over the bay, we'd call them bagels.",
  "17": "I only know 25 letters of the alphabet. I don't know y.",
  "18": "How does the moon cut his hair?" "Eclipse it.",
  "19": "What did one wall say to the other?" "I'll meet you at the corner.",
  "20": "What did the zero say to the eight?" "That belt looks good on you.",
  "21": "A skeleton walks into a bar and says, 'Hey, bartender. I'll have one beer and a mop.'",
  "22": "Where do fruits go on vacation?" "Pear-is!",
  "23": "I asked my dog what's two minus two. He said nothing.",
  "24": "What did Baby Corn say to Mama Corn?" "Where's Pop Corn?",
  "25": "What's the best thing about Switzerland?" "I don't know, but the flag is a big plus.",
  "26": "What does a sprinter eat before a race?" "Nothing, they fast!",
  "27": "Where do you learn to make a banana split?" "Sundae school.",
  "28": "What has more letters than the alphabet?" "The post office!",
  "29": "Dad, did you get a haircut?" "No, I got them all cut!",
  "30": "What do you call a poor Santa Claus?" "St. Nickel-less.",
  "31": "I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.",
  "32": "Where do boats go when they're sick?" "To the boat doc.",
  "33": "I don't trust those trees. They seem kind of shady.",
  "34": "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right!",
  "35": "How do you get a squirrel to like you? Act like a nut.",
  "36": "Why don't eggs tell jokes? They'd crack each other up.",
  "37": "I don't trust stairs. They're always up to something.",
  "38": "What do you call someone with no body and no nose? Nobody knows.",
  "39": "Did you hear the rumor about butter? Well, I'm not going to spread it!",
  "40": "Why couldn't the bicycle stand up by itself? It was two tired.",
  "41": "What did one hat say to the other?" "Stay here! I'm going on ahead.",
  "42": "Why did Billy get fired from the banana factory? He kept throwing away the bent ones.",
  "43": "Dad, can you put my shoes on?" "No, I don't think they'll fit me.",
  "44": "Why can't a nose be 12 inches long? Because then it would be a foot.",
  "45": "What does a lemon say when it answers the phone?" "Yellow!",
  "46": "This graveyard looks overcrowded. People must be dying to get in.",
  "47": "What kind of car does an egg drive?" "A yolkswagen.",
  "48": "Dad, can you put the cat out?" "I didn't know it was on fire.",
  "49": "How do you make 7 even?" "Take away the s.",
  "50": "How does a taco say grace?" "Lettuce pray.",
  "51": "What time did the man go to the dentist? Tooth hurt-y.",
  "52": "Why didn't the skeleton climb the mountain?" "It didn't have the guts.",
  "53": "What do you call it when a snowman throws a tantrum?" "A meltdown.",
  "54": "How many tickles does it take to make an octopus laugh? Ten tickles.",
  "55": "I have a joke about chemistry, but I don't think it will get a reaction.",
  "56": "What concert costs just 45 cents? 50 Cent featuring Nickelback!",
  "57": "What does a bee use to brush its hair?" "A honeycomb!",
  "58": "How do you make a tissue dance? You put a little boogie in it.",
  "59": "Why did the math book look so sad? Because of all of its problems!",
  "60": "What do you call cheese that isn't yours? Nacho cheese.",
  "61": "My dad told me a joke about boxing. I guess I missed the punch line.",
  "62": "What kind of shoes do ninjas wear? Sneakers!",
  "63": "How does a penguin build its house? Igloos it together.",
  "64": "I used to be addicted to soap, but I'm clean now.",
  "65": "A guy walks into a bar...and he was disqualified from the limbo contest.",
  "66": "You think swimming with sharks is expensive? Swimming with sharks cost me an arm and a leg.",
  "67": "When two vegans get in an argument, is it still called a beef?",
  "68": "I ordered a chicken and an egg from Amazon. I'll let you know...",
  "69": "Do you wanna box for your leftovers?" "No, but I'll wrestle you for them.",
  "70": "That car looks nice but the muffler seems exhausted.",
  "71": "Shout out to my fingers. I can count on all of them.",
  "72": "If a child refuses to nap, are they guilty of resisting a rest?",
  "73": "What country's capital is growing the fastest?" "Ireland. Every day it's Dublin.",
  "74": "I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea.",
  "75": "Did you know corduroy pillows are in style? They're making headlines.",
  "76": "Did you hear about the kidnapping at school? It's okay, he woke up.",
  "77": "A cheeseburger walks into a bar. The bartender says, 'Sorry, we don't serve food here.'",
  "78": "I once got fired from a canned juice company. Apparently I couldn't concentrate.",
  "79": "I used to play piano by ear. Now I use my hands.",
  "80": "Have you ever tried to catch a fog? I tried yesterday but I mist.",
  "81": "I'm on a seafood diet. I see food and I eat it.",
  "82": "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "83": "I made a pencil with two erasers. It was pointless.",
  "84": "How do you make a Kleenex dance? Put a little boogie in it!",
  "85": "I'm reading a book about anti-gravity. It's impossible to put down!",
  "86": "Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.",
  "87": "I've got a great joke about construction, but I'm still working on it.",
  "88": "I used to hate facial hair...but then it grew on me.",
  "89": "I decided to sell my vacuum cleaner—it was just gathering dust!",
  "90": "I had a neck brace fitted years ago and I've never looked back since.",
  "91": "You know, people say they pick their nose, but I feel like I was just born with mine.",
  "92": "What's brown and sticky? A stick.",
  "93": "Why can't you hear a psychiatrist using the bathroom? Because the 'P' is silent.",
  "94": "What do you call an elephant that doesn't matter? An irrelephant.",
  "95": "What do you get from a pampered cow? Spoiled milk.",
  "96": "I like telling Dad jokes. Sometimes he laughs!",
  "97": "What's the best smelling insect?" "A deodor-ant.",
  "98": "I used to be a personal trainer. Then I gave my too weak notice.",
  "99": "Did I tell you the time I fell in love during a backflip? I was heels over head!",
  "100": "If a child refuses to sleep during nap time, are they guilty of resisting a rest?",
  "101": "I ordered a chicken and an egg online. I’ll let you know.",
  "102": "It takes guts to be an organ donor.",
  "103": "If you see a crime at an Apple Store, does that make you an iWitness?",
  "104": "I'm so good at sleeping, I can do it with my eyes closed!",
  "105": "I was going to tell a time-traveling joke, but you guys didn't like it.",
  "106": "What happens when a strawberry gets run over crossing the street?" "Traffic jam.",
  "107": "What do you call two monkeys that share an Amazon account?" "Prime mates.",
  "108": "What do you call a pony with a sore throat?" "A little hoarse.",
  "109": "Where do math teachers go on vacation?" "Times Square.",
  "110": "Whenever I try to eat healthy, a chocolate bar looks at me and Snickers.",
  "111": "What does garlic do when it gets hot?" "It takes its cloves off.",
  "112": "What's a robot's favorite snack?" "Computer chips.",
  "113": "How much does it cost Santa to park his sleigh?" "Nothing, it's on the house.",
  "114": "Mountains aren't just funny. They're hill areas.",
  "115": "What do clouds wear?" "Thunderwear.",
  "116": "Why are piggy banks so wise?" "They're filled with common cents.",
  "117": "Why is Peter Pan always flying?" "He neverlands.",
  "118": "How do you get a good price on a sled?" "You have toboggan.",
  "119": "How can you tell if a tree is a dogwood tree?" "By its bark.",
  "120": "I used to hate facial hair, but then it grew on me.",
  "121": "It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa.",
  "122": "What do you call a hot dog on wheels?" "Fast food!",
  "123": "Where do young trees go to learn?" "Elementree school.",
  "124": "Did you hear about the circus fire? It was in tents.",
  "125": "Can February March? No, but April May!",
  "126": "How do lawyers say goodbye? We'll be suing ya!",
  "127": "Wanna hear a joke about paper? Never mind—it's tearable.",
  "128": "What's the best way to watch a fly fishing tournament? Live stream.",
  "129": "Spring is here! I got so excited I wet my plants.",
  "130": "I could tell a joke about pizza, but it's a little cheesy.",
  "131": "Don't trust atoms. They make up everything!",
  "132": "When does a joke become a dad joke? When it becomes apparent.",
  "133": "I wouldn't buy anything with velcro. It's a total rip-off.",
  "134": "What’s an astronaut’s favorite part of a computer? The space bar.",
  "135": "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
  "136": "Why are elevator jokes so classic and good? They work on many levels.",
  "137": "Why do bees have sticky hair? Because they use a honeycomb.",
  "138": "What do you call a fake noodle? An impasta.",
  "139": "Which state has the most streets? Rhode Island.",
  "140": "What did the coffee report to the police? A mugging.",
  "141": "What did the fish say when he hit the wall? Dam.",
  "142": "Is this pool safe for diving? It deep ends.",
}

